USE DentistOffice;
DROP TABLE PaysFor;
DROP TABLE Claim;
DROP TABLE Payment;
DROP TABLE Bill;
DROP TABLE Treatment;
DROP TABLE Visit;
DROP TABLE Appointment;
DROP TABLE Dentist;
DROP TABLE Patient;
DROP TABLE InsuranceCompany;
DROP VIEW billStatusView;
DROP FUNCTION getTotal;
DROP FUNCTION getPaid;
DROP FUNCTION getPayer;
DROP SEQUENCE treatmentSequence;